### ISSUE TITLE
Documentation: New (easy) instructions for CodeIgniter-Kint-Integration

### ISSUE THREAD

**Issue by Tilogorn** [kint-php/kint#180]
As the "plugin" you linked for CodeIgniter (https://github.com/adriangonzales/codeigniter-kint) is unmaintained since 3-4 years, I'll just leave instructions for current versions of both tools. It's very easily done in three steps. One can simply replace new versions of Kint by himself without depending on a third maintainer.

Maybe you can quote the following instructions in your docs (feel free to correct my english, it's not my native language)
## Instructions for CodeIgniter-Kint-Integration
1. Extract the Kint-Repository and place the resulting folder in `application/libraries/`
2. Rename the class-file from `Kint.class.php` to `Kint.php`
3. Autoload the library: Add `kint-master/Kint` to your `libraries`-array in `application/config/autoload.php`. Should look like this (beside other autoloaded libs): `$autoload['libraries'] = array('kint-master/Kint');`
4. Done! Use `d($var)` and all other methods everywhere in your code as you used `var_dump($var)` before (no loading needed, no calling on objects or the like)

**Comment by raveren** [comment]
Thanks, why not create your own plugin with your fixes? I'd link it in the docs..

**Comment by Tilogorn** [comment]
You're welcome! 
A plugin would be inefficient: I would have to reliably repeat step 2 (the only one you can do remotely - just renaming the class-file) every time in the future when you publish a new release. That's error-prone (like the situation is as now). As a compromise I could create a repo with just a (more detailed) Readme-file. Will that meet your demands?

**Comment by raveren** [comment]
Does the file _have_ to be named that? If so your plugin could have a file named `Kint.php` which included the correct one from a subfolder or whatever

**Comment by Tilogorn** [comment]
Yes, it has to be. The CodeIgniter-Loading-Engine can't handle the additional `.` in the filename. But your suggestion is good, I will post a link here as soon as I implemented and tested it.

**Comment by rezman** [comment]
Hi Tilogorn.
I followed the CodeIgniter integration procedure above but still cannot get the graphical boxes loaded in my script when dumping codes. It seems like there is still a wrapper issue with mine. Any suggestions for a fix?

**Comment by Tilogorn** [comment]
Pay attention that you follow Step 1 exactly. The whole repo-folder including the css files (kint-master/view/compiled) should be placed in application/libraries (see attached screenshot). I can't say more without any error... (maybe there appears sth in `application/logs/` or in the browser console)

![bildschirmfoto 2016-01-22 um 08 46 31](https://cloud.githubusercontent.com/assets/7524854/12505200/ef5214d6-c0e4-11e5-9d4e-41b070b2ba30.png)

**Comment by rezman** [comment]
I've followed the steps exactly as you have above with the installation. The problem is when I place a dump code in the page I'm editing, the actual dump code will show up when I refresh my browser. Example: d($rent_price) Is this all that is required for the graphic box to be displayed? This script that I'm modifying is a large RE listing script built in an HMVC version of Codeigniter. Could the complexity of the script be the cause of problem?

**Comment by Tilogorn** [comment]
I don't understand your problem exactly. So the dump with Kint works, but it's not nicely formatted? (which led me to the guess that you misplaced your .css-files). Maybe you can attach a screenshot of the dump (with opened JavaScript-Console).

**Comment by Steveb-p** [comment]
> I've followed the steps exactly as you have above with the installation. The problem is when I place a dump code in the page I'm editing, the actual dump code will show up when I refresh my browser. Example: d($rent_price) Is this all that is required for the graphic box to be displayed? This script that I'm modifying is a large RE listing script built in an HMVC version of Codeigniter. Could the complexity of the script be the cause of problem?

You're obviously missing the <?php tag.

**Comment by jnvsor** [comment]
Since there's pretty much nothing out there that supports kint 2.0 at this time, I'm closing the third-party-plugin documentation issues.

I probably won't add the list back until there are a decent few to list too.

**Comment by bert126** [comment]
Is it possible to make the last version also working from Code Igniter?
I have followed your procedure (no renaming needed by the way), but CI continues telling me 
"Unable to load the requested class: Kint"
Thank you.

**Comment by Tilogorn** [comment]
@bert126 It's a lot easier now, just use composer:

1. See the section "Composer auto-loading" in your Codeigniter `config.php` file
2. Install kint with composer

**Comment by mlopezcoria** [comment]
Just wanna share how I installed kint on CodeIgniter 3:

1. I created a new folder under `application` named `third_party`.
2. Then I created a `composer.json` file in this folder with the following content:
```
{
    "require": {
        "kint-php/kint" :"^3.1",
        "kint-php/kint-js" : "^2"
    }   
}
```
3. I modified the `config/config.php` file like this:
`$config['composer_autoload'] = 'application/third_party/vendor/autoload.php';`
4. That all!

Hope it helps!

**Comment by ItsJustATypo** [comment]
### I installed in Codeigniter 3 by using Composer.  Here are the steps:

Before starting, I had already installed Composer and had the following folders:

```
/
  /application 
  /vendor
      /composer
      autoload.php
  composer.json
```

1. From the "/'" root folder, run **`composer require kint-php/kint`**

The Composer output was:

```
Using version ^3.1 for kint-php/kint
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing kint-php/kint (3.1): Downloading (100%)
kint-php/kint suggests installing kint-php/kint-twig (Provides d() and s() functions in twig templates)
kint-php/kint suggests installing kint-php/kint-js (Provides a simplified dump to console.log())
kint-php/kint suggests installing symfony/polyfill-iconv (Replacement for ext-iconv if missing)
kint-php/kint suggests installing symfony/polyfill-ctype (Replacement for ext-ctype if missing)
Writing lock file
Generating autoload files
```

Within the `/vendor` folder, there should now be a folder `kint-php`, like this:
```
/application 
/vendor
    /composer
    /kint-php
    autoload.php
```
2. Run **`composer dump-autoload`**.  In `autoload.php`, the "require" statement should include:
```
{
    "require": {
        "kint-php/kint": "^3.1"
    },
}
```
3.  Upload these files and folders to the server:
```
/application 
/vendor
    /composer        <---- upload to server
    /kint-php        <---- upload to server
    autoload.php    <---- upload to server
composer.json      <---- upload to server
```
4. In your CodeIgniter config file `/application/config/config/php`, uncomment and edit this setting:

```$config['composer_autoload'] = 'vendor/autoload.php';```

5. Save and upload the `config.php` to the server.

6.  In a CodeIgniter controller, such as "welcome.php`, add a function to call kint, like this:
```
class Welcome extends CI_Controller{
    function kint()
    {
      d('Hello world');
    }
}
```
7. Upload this controller to your server.
8.  call the controller, such as `example.com/index.php/welcome/kint`
It may look like nothing happened, but look at the bottom of your browser window and you should see a light blue stripe with "+Kint".  Click the "+" sign and you're good to go!
