### ISSUE TITLE
Error message: Cannot access non-public member

### ISSUE THREAD

**Issue by picasso** [kint-php/kint#359]
I get this error. As I noticed, this only applies to **static private** property

`An exception (ReflectionException) was thrown in phar://<ROOT>/wp-content/plugins/zu-plus/includes/debug/kint.phar/src/Parser/ClassStaticsPlugin.php on line 94 while executing Kint Parser Plugin "Kint\Parser\ClassStaticsPlugin". Error message: Cannot access non-public member zu_Plus::$zukit_root`

What could be the problem?

**Comment by jnvsor** [comment]
Hi @picasso, what version of kint are you using? Can you produce a small test case for this?

**Comment by picasso** [comment]
It's hard to tell which version I'm using. The one that I downloaded from the site using the link. What version is this? As I wrote in another request, it is not so easy to understand which version.

what do I need to do for "small test case for this"?

**Comment by jnvsor** [comment]
Hi @picasso I reproduced and fixed the issue, I just pushed it to master. Looks like the 8.1-dev tests aren't working so I'll have to fix them, but the phar should now work. Could you try it out and see?

**Comment by picasso** [comment]
thanks @jnvsor! I'll try today and let you know

**Comment by picasso** [comment]
I used phar from [this link](https://raw.githubusercontent.com/kint-php/kint/master/build/kint.phar) but errors are still present

How can I check that I am using the correct phar? File size is the same

**Comment by jnvsor** [comment]
It should have the md5sum 334ff1cfa06a3085b6cbe5e6b6db61b0

**Comment by picasso** [comment]
yes, it has 
`MD5 (kint.phar) = 334ff1cfa06a3085b6cbe5e6b6db61b0`

**Comment by jnvsor** [comment]
Has the error message changed at all? Because if it's still saying that it's line 94 then you're probably including the old file (as per https://github.com/kint-php/kint/commit/46878c5cb94e5f76c5f49e81cbd1cb15c4fb4d53)

**Comment by picasso** [comment]
you gave me an idea ... maybe the phar was cached somewhere. I restarted everything and now there is no error. Thanks!

By the way, now I noticed and see that **static private** properties are not displayed in the "**Properties**" tab. This is normal?

**Comment by jnvsor** [comment]
Good to hear it.

Static properties should be displayed in a separate tab, because they are local to the class, not the instance. You should see them in a tab labeled "Static class properties" along with consts

**Comment by picasso** [comment]
![Screenshot 2021-04-06 at 20 02 37](https://user-images.githubusercontent.com/399395/113757565-0b054680-9713-11eb-90fe-901017a66c54.png)

I do not see such a tab

**Comment by jnvsor** [comment]
That's weird, but I notice you're using a 3rd party theme. Did you make that yourself or is kint being run through a separate system? Can you dump `Kint::$plugins` for me?

**Comment by picasso** [comment]
yes, that's my theme. I embedded Knit into the [query monitor](https://github.com/johnbillion/query-monitor) for WordPress

![Screenshot 2021-04-06 at 20 09 25](https://user-images.githubusercontent.com/399395/113758525-46ecdb80-9714-11eb-8da8-fa0403a34038.png)

**Comment by jnvsor** [comment]
Sorry I'm trying to find this `zu_PlusDebugBar` class to help debug this but google is turning nothing up.

Do you know where I can see the source for a look?

**Comment by picasso** [comment]
this is my class. wait, in 10 minutes I will make the repository public on github

**Comment by picasso** [comment]
here is this link
[zu-plus](https://github.com/picasso/zu-plus)

you might be interested to see the method `kint_log()`
in `includes/debug/trait-output.php`
there the call to Kint occurs

**Comment by jnvsor** [comment]
So I just ran this while commenting out the wp function calls to just get a minimal test result and it seems to work fine here (Besides the undefined const):

```php
<?php

error_reporting(E_ALL);
ini_set('display_errors', true);

require __DIR__ . '/../../projects/kint/vendor/autoload.php';

error_reporting(E_ALL);
ini_set('display_errors', true);

include __DIR__.'/picasso/zu-plus-master/zukit/zukit-singleton.php';
include __DIR__.'/picasso/zu-plus-master/includes/debug/debug-bar.php';

$a = zu_PlusDebugBar::instance();

Kint::$enabled_mode = true;

d($a);
```

![image](https://user-images.githubusercontent.com/5260644/113763443-37b46080-9709-11eb-849f-1e93f854817e.png)

So it would seem to be working here.

**Comment by picasso** [comment]
If you tell me where the static properties processing (file and approximate line) takes place, then I can insert debugging in my instance and see what is the difference between your case and mine.

and by the way, what is the version number that I am currently using? This is definitely not 3.3.

**Comment by jnvsor** [comment]
You're using master. The code you're looking for is `src/Parser/ClassStaticsPlugin.php`. If it gets to the `addRepresentation` call it should be working

**Comment by picasso** [comment]
I understand that I'm using master ... but which version is it? 4.alpha?

Ok, I understand what the problem is. I sent you a screenshot from the version where there was an error with the static properties. In the version where there is no error, then the tab is in place. I'm sorry that because of my mistake I wasted your time.

![Screenshot 2021-04-06 at 23 31 10](https://user-images.githubusercontent.com/399395/113781017-52e69680-9730-11eb-8884-91e818ffafa5.png)

But in your example case, for some reason strange numbers of the number of methods and properties. In my screenshot the numbers are more correct. But it probably doesn't matter anymore ... the main thing is that everything works. 

**Thanks!**
