### ISSUE TITLE
PHP 8.1 - TypeError Cannot assign stdClass to reference held by property ...

### ISSUE THREAD

**Issue by pjsde** [kint-php/kint#390]
In PHP 8.1 when trying dump an variable i get the error: ``TypeError: Cannot assign stdClass to reference held by property GPFramework\Libraries\Menus\MenuCollection::$items of type array`` at kint-php\kint\src\Parser\Parser.php at line 527

my code is:

```
Kint::$mode_default        = Kint::MODE_RICH;
Kint::$display_called_from = false;

$kint = @Kint::dump($menus);
```

the content of ``$menus`` is:
```
Array
(
    [ci4-framework] => GPFramework\Libraries\Menus\MenuCollection Object
        (
            [name:protected] => ci4-framework
            [title:protected] => CI4 Framework
            [url:protected] => 
            [altText:protected] => 
            [order:protected] => 0
            [permission:protected] => Array
                (
                )

            [faIcon:protected] => 
            [iconUrl:protected] => 
            [isActive:protected] => 
            [activeUrl:protected] => 
            [visible:protected] => 1
            [collapsible:protected] => 
            [items:protected] => Array
                (
                    [components] => GPFramework\Libraries\Menus\MenuItem Object
                        (
                            [name:protected] => components
                            [title:protected] => Components
                            [url:protected] => https://projects.local/gp-base-ci4-framework/sources/public_html/admin/pt
                            [altText:protected] => 
                            [order:protected] => 0
                            [permission:protected] => Array
                                (
                                )

                            [faIcon:protected] => 
                            [iconUrl:protected] => 
                            [isActive:protected] => 
                            [activeUrl:protected] => 
                            [visible:protected] => 1
                        )

                    [menus] => GPFramework\Libraries\Menus\MenuItem Object
                        (
                            [name:protected] => menus
                            [title:protected] => Menus
                            [url:protected] => https://projects.local/gp-base-ci4-framework/sources/public_html/admin/pt
                            [altText:protected] => 
                            [order:protected] => 0
                            [permission:protected] => Array
                                (
                                )

                            [faIcon:protected] => 
                            [iconUrl:protected] => 
                            [isActive:protected] => 
                            [activeUrl:protected] => 
                            [visible:protected] => 1
                        )

                )

        )

)
```

Is this a bug or am i doing something wrong?

**Comment by jnvsor** [comment]
Should be fixed in 055630e77a9ae625968ade09addb0bd57ce1f4b3

**Comment by JPustkuchen** [comment]
Thanks @jnvsor,

we're using 5.0.6 and the issue still appears. I guess it should be fixed in this version?
For us it happens in Drupal 10.

The partial backtrace is:
```
TypeError: Cannot assign stdClass to reference held by property Symfony\Component\HttpFoundation\Session\Flash\FlashBag::$flashes of type array in Kint\Parser\Parser->parseArray() (line 377 of /vendor/kint-php/kint/src/Parser/Parser.php).

Kint\Parser\Parser->parse() (Line: 565)
Kint\Parser\Parser->parseObject() (Line: 138)
Kint\Parser\Parser->parse() (Line: 565)
Kint\Parser\Parser->parseObject() (Line: 138)
Kint\Parser\Parser->parse() (Line: 565)
Kint\Parser\Parser->parseObject() (Line: 138)
Kint\Parser\Parser->parse() (Line: 565)
Kint\Parser\Parser->parseObject() (Line: 138)
Kint\Parser\Parser->parse() (Line: 285)
Kint\Kint->dumpVar() (Line: 268)
Kint\Kint->dumpAll() (Line: 575)
Kint\Kint::dump() (Line: 64)
Drupal\devel\Plugin\Devel\Dumper\Kint->export() (Line: 105)
Drupal\devel\DevelDumperManager->export() (Line: 115)
Drupal\devel\DevelDumperManager->message() (Line: 183)
Drupal\devel\Twig\Extension\Debug->message() (Line: 44)
__TwigTemplate_1bb3a20a3f4847fc1af463271334acbf->doDisplay() (Line: 394)
Twig\Template->displayWithErrorHandling() (Line: 367)
Twig\Template->display() (Line: 379)
Twig\Template->render() (Line: 40)
Twig\TemplateWrapper->render() (Line: 53)
twig_render_template() (Line: 372)
```

Does that help?

Seems like it appeared with the Drupal 10 Upgrade which uses Symfony 6.2. With Drupal 9 we never had that issue before. Should this be reopened?

**Comment by jnvsor** [comment]
While it seems obvious, you can't assign a value to a reference of a typed property of the wrong type. Since copying arrays and assigning instances to each member was how we detected references all I had to do was throw a try catch around it to stop it failing on every object with a typed property.

I didn't realize someone could throw a reference to a typed property into an array and pass that into kint (Even though that's basically what kint is doing itself...) so we basically had to do the same thing for arrays too.

Please confirm that this works @JPustkuchen 

---

Example code

```php
<?php

class test {
    public int $v;
}

$t = new test();
$t->v = 4;

$a['val'] = &$t->v;

$a['val'] = 'test';
```

**Comment by JPustkuchen** [comment]
@jnvsor WHAO, you're Speedy Gonzales! Fastest mouse in Mexico 🚀 
(No idea if that cartoon has the same name anywhere in the world, like in Germany xD)

Yes, perfect! Working just fine, thanks for the lightning fast fix!
